version: '3'
services:
#  redis:
#    image: "redis"
#    container_name: redis63797
#    ports:
#      - "63797:6379"
  postgres:
    image: "postgres"
    container_name: postgres5432
    ports:
      - "5432:5432"
    environment:
      - "POSTGRESQL_USERNAME=postgres"
      - "POSTGRES_PASSWORD=testOnly"
